### ISSUE TITLE
Kernel 6.1

### ISSUE THREAD

**Issue by kruegerha** [cschramm/irda#10]
the upcoming debian 12 (bookworm) uses kernel 6.1 as default, therefore I tried to compile the irda modules for this kernel and ran into this error:
error: implicit declaration of function ‘kernel_termios_to_user_termios_1'

Are there any plans for kernel 6.1 yet, are there any major obstacles?

make -C src
make: Entering directory '/home/kruegerh/src/IRDA-HK/irda/src'
make -C "/lib/modules/6.1.0-3-amd64/build" M="$(pwd)"
make[1]: Entering directory '/usr/src/linux-headers-6.1.0-3-amd64'
  CC [M]  /home/kruegerh/src/IRDA-HK/irda/src/net/irlan/irlan_common.o
  CC [M]  /home/kruegerh/src/IRDA-HK/irda/src/net/irlan/irlan_eth.o
  CC [M]  /home/kruegerh/src/IRDA-HK/irda/src/net/irlan/irlan_event.o
  CC [M]  /home/kruegerh/src/IRDA-HK/irda/src/net/irlan/irlan_client.o
  CC [M]  /home/kruegerh/src/IRDA-HK/irda/src/net/irlan/irlan_provider.o
  CC [M]  /home/kruegerh/src/IRDA-HK/irda/src/net/irlan/irlan_filter.o
  CC [M]  /home/kruegerh/src/IRDA-HK/irda/src/net/irlan/irlan_provider_event.o
  CC [M]  /home/kruegerh/src/IRDA-HK/irda/src/net/irlan/irlan_client_event.o
  LD [M]  /home/kruegerh/src/IRDA-HK/irda/src/net/irlan/irlan.o
  CC [M]  /home/kruegerh/src/IRDA-HK/irda/src/net/irnet/irnet_ppp.o
/home/kruegerh/src/IRDA-HK/irda/src/net/irnet/irnet_ppp.c: In function ‘dev_irnet_ioctl’:
/home/kruegerh/src/IRDA-HK/irda/src/net/irnet/irnet_ppp.c:769:11: error: implicit declaration of function ‘kernel_termios_to_user_termios_1’ [-Werror=implicit-function-declaration]
  769 |       if(!kernel_termios_to_user_termios_1((struct termios __user *)argp, &ap->termios))
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/kruegerh/src/IRDA-HK/irda/src/net/irnet/irnet_ppp.c:785:11: error: implicit declaration of function ‘user_termios_to_kernel_termios_1’ [-Werror=implicit-function-declaration]
  785 |       if(!user_termios_to_kernel_termios_1(&ap->termios, (struct termios __user *)argp))
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[4]: *** [/usr/src/linux-headers-6.1.0-3-common/scripts/Makefile.build:255: /home/kruegerh/src/IRDA-HK/irda/src/net/irnet/irnet_ppp.o] Fehler 1
make[3]: *** [/usr/src/linux-headers-6.1.0-3-common/scripts/Makefile.build:505: /home/kruegerh/src/IRDA-HK/irda/src/net/irnet] Fehler 2
make[2]: *** [/usr/src/linux-headers-6.1.0-3-common/scripts/Makefile.build:505: /home/kruegerh/src/IRDA-HK/irda/src/net] Fehler 2
make[1]: *** [/usr/src/linux-headers-6.1.0-3-common/Makefile:2017: /home/kruegerh/src/IRDA-HK/irda/src] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.1.0-3-amd64'
make: *** [Makefile:6: default] Error 2
make: Leaving directory '/home/kruegerh/src/IRDA-HK/irda/src'

**Comment by kruegerha** [comment]
please ignore above report! 
I did not have the latest commits checked out

**Comment by cschramm** [comment]
Ignored. :smirk: You're welcome.
