### ISSUE TITLE
Cannot allocate memory (newer kernels)

### ISSUE THREAD

**Issue by thoschi** [cschramm/irda#18]
First of all: I managed to get irda to work for years thanks to this repo - great work!

In Ubuntu 24.10 (Kernel 6.11.0-9-generic) the installation works well but for the first time loading the kernel modules fails saying `Cannot allocate memory`.

`dmesg` shows:
```
ET: Registered PF_IRDA protocol family
sysctl table check failed: net/irda/(null) procname is null
sysctl table check failed: net/irda/(null) No proc_handler
```

Any idea? If I can help debugging I will do.
Best regards
Thomas

**Comment by cschramm** [comment]
Thanks for reporting. I do not actually use irda at the moment and this totally slipped through.

It looks like the sysctl registration broke in 6.10.

Can you try the `dev` branch? https://github.com/cschramm/irda/commit/7920262f35b01a3d995a3976570ff30c7732b274

**Comment by thoschi** [comment]
My use of irda is also quite sporadic - an otherwise well working diving computer I do not want to give up. For me you offering this repo is a true act of sustainability! Thank you so much for it!

Just did a quick check, changing the branch of my little install/load script - and no more errors so far . Will do some more testing next days but it seems to work fine! Thank you again :-)

Best regards
Thomas

**Comment by cschramm** [comment]
Great. :slightly_smiling_face: I pushed the fix to `main`.
