### ISSUE TITLE
userspace tools?

### ISSUE THREAD

**Issue by nonchip** [cschramm/irda#2]
you mention `irattach` multiple times in the repo, how would you suggest getting those userspace tools on a "too modern for irda" distro?

**Comment by cschramm** [comment]
Good question as `irda-utils` is vanishing from distros. I personally haven't encountered the problem yet as I used to use a Debian system with testing repositories that just had the `irda-utils` package from stretch in place and I never removed it and nowadays I'm mostly on Arch Linux and there is thankfully an `irda-utils` package in AUR.

If you do not have such options... the official download URL for the latest (i.e. 07/2006) version is still https://sourceforge.net/projects/irda/files/irda-utils/0.9.18/irda-utils-0.9.18.tar.gz/download and compiling should not be a showstopper. A look at [the AUR PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=irda-utils) might be of help, at least they patch some paths.

**Comment by mnhauke** [comment]
openSUSE still ships "irda-utils" with the "irda" package.
You can have a look at https://build.opensuse.org/package/show/Base:System/irda to get an idea what build options they are using and which patches get applied on top of irda-utils-0.9.18.tar.gz
