### ISSUE TITLE
Appletalk already needed in Linux 5.15

### ISSUE THREAD

**Issue by mirage83-ger** [cschramm/irda#8]
I spend two days to figure out that the CONFIG_ATALK is already needed in Linux 5.15. So please adapt the README accordingly.

Furthermore I would suggest you add a config test (e.g. using IS_ENABLED()) so building will fail if CONFIG_ATALK isn't enabled.

**Comment by cschramm** [comment]
Sorry for your hassle. I fixed the README and dropped `CONFIG_IRDA` so that compilation should fail just like it started to with 5.17.
